vuldb_portfolio/app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.Top.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user/create/', views.UserCreate.as_view(), name='user_create'),
    path('user/create/done/', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user/create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user/detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user/update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('user/delete/<int:pk>/', views.UserDelete.as_view(), name='user_delete'),
    path('user/delete/done/', views.UserDeleteDone.as_view(), name='user_delete_done'),
    path('password/change/', views.PasswordChange.as_view(), name='password_change'),
    path('password/change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password/reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password/reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password/reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password/reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),
    path('app/create/', views.AppNameCreate.as_view(), name='app_create'),
    path('app/list/', views.AppNameList.as_view(), name='app_list'),
    path('app/detail/<int:pk>/', views.AppNameDetail.as_view(), name='app_detail'),
    path('app/update/<int:pk>/', views.AppNameUpdate.as_view(), name='app_update'),
    path('app/delete/<int:pk>/', views.AppNameDelete.as_view(), name='app_delete'),
    path('version/create/', views.VersionCreate.as_view(), name='version_create'),
    path('version/list/', views.VersionList.as_view(), name='version_list'),
    path('version/detail/<int:pk>', views.VersionDetail.as_view(), name='version_detail'),
    path('version/update/<int:pk>', views.VersionUpdate.as_view(), name='version_update'),
    path('version/delete/<int:pk>', views.VersionDelete.as_view(), name='version_delete'),
    path('app_version/create/', views.AppVersionCreate.as_view(), name='app_version_create'),
    path('app_version/list/', views.AppVersionList.as_view(), name='app_version_list'),
    path('app_version/detail/<int:pk>/', views.AppVersionDetail.as_view(), name='app_version_detail'),
    path('app_version/update/<int:pk>/', views.AppVersionUpdate.as_view(), name='app_version_update'),
    path('app_version/delete/<int:pk>/', views.AppVersionDelete.as_view(), name='app_version_delete'),
    path('vulnerability/create/', views.VulnerabilityCreate.as_view(), name='vul_create'),
    path('vulnerability/list/', views.VulnerabilityList.as_view(), name='vul_list'),
    path('vulnerability/detail/<int:pk>', views.VulnerabilityDetail.as_view(), name='vul_detail'),
    path('vulnerability/update/<int:pk>', views.VulnerabilityUpdate.as_view(), name='vul_update'),
    path('vulnerability/delete/<int:pk>', views.VulnerabilityDelete.as_view(), name='vul_delete'),
]

vuldb_portfolio/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

vuldb_portfolio/users/models.py
from django.db import models
from django.apps import apps
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

# Create your models here.

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, username, email, password, **extra_fields):
        """
        Create and save a user with the given email, password.
        """
        if not username:
            raise ValueError('The given username must be set.')
        if not email:
            raise ValueError('The given email must be set.')
        email = self.normalize_email(email)
        GlobalUsername = apps.get_model(self.model._meta.app_label, self.model._meta.object_name)
        username = GlobalUsername.normalize_username(username)
        user = self.model(username=username, email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(self, username, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(username, email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    """
    Custom user model
    """
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required 150 characters or fewwer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists.")
        },
    )

    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active.'
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """
        return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    

vuldb_portfolio/users/views.py
from django.shortcuts import render

# Create your views here.

vuldb_portfolio/app/templates/app/app_create.html
{% extends "app/base.html" %}
{% block title %} 新規アプリ登録 {% endblock %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">登録</button>
</form>
{% endblock %}

vuldb_portfolio/app/templates/app/app_detail.html
{% extends "app/base.html" %}
{% block title %} アプリ{{ object.name }}の詳細 {% endblock %}
{% block content %}
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>アプリ名</th>
            <th>ベンダURL</th>
            <th>編集</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ object.name }}</td>
            <td><a href="{{ object.url }}">{{ object.url }}</a></td>
            <td>
                <div class="btn-group" role="group" aria-label="Basic example">
                    <a href="{% url 'app:app_update' object.pk %}" class="btn btn-warning">修正</a>
                    <a href="{% url 'app:app_delete' object.pk %}" class="btn btn-danger">削除</a>
                </div>
            </td>
        </tr>
    </tbody>
</table>
{% endblock %}

vuldb_portfolio/app/templates/app/app_update.html
{% extends "app/base.html" %}
{% block title %} アプリ{{ object.name }}の修正 {% endblock %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">修正</button>
</form>
{% endblock %}

vuldb_portfolio/app/templates/app/app_version_create.html
{% extends "app/base.html" %}
{% block title %} 新規アプリ/バージョン登録 {% endblock %}
{% block content %}
<div class="text-right">
    <a href="{% url 'app:app_create'%}" class="btn btn-outline-primary">アプリ新規登録</a>
    <a href="{% url 'app:version_create'%}" class="btn btn-outline-primary">バージョン新規登録</a>
</div>
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">登録</button>
</form>
{% endblock %}

vuldb_portfolio/app/templates/app/app_version_detail.html
{% extends "app/base.html" %}
{% block title %} {{ object.name }}/{{ object.version }}の詳細 {% endblock %}
{% block content %}
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>アプリ名</th>
            <th>バージョン</th>
            <th>編集</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ object.name }}</td>
            <td>{{ object.version }}</td>
            <td>
                <div class="btn-group" role="group" aria-label="Basic example">
                    <a href="{% url 'app:app_version_update' object.pk %}" class="btn btn-warning">修正</a>
                    <a href="{% url 'app:app_version_delete' object.pk %}" class="btn btn-danger">削除</a>
                </div>
            </td>
        </tr>
    </tbody>
</table>
{% endblock %}

vuldb_portfolio/app/templates/app/email_change_done.html
{% extends "app/base.html" %}
{% block title %} メールアドレス変更完了 {% endblock %}
{% block content %}
<p>
    確認メールに記載されているリンクをクリックすると、アドレスが変更されます。
</p>
{% endblock %}

vuldb_portfolio/app/templates/app/login.html
{% extends "app/base.html" %}
{% block title %} ログイン {% endblock %}
{% block content %}
<div class="row">
    <!-- 左側、ログインエリア -->
    <div class="card col-md-6">
        <div class="card-body">
            <form action="{% url 'app:login' %}" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <hr>
                {% endfor %}
                <button type="submit" class="btn btn-success btn-lg btn-block" >ログイン</button>
                <input type="hidden" name="next" value="{{ next }}" />
                {% csrf_token %}
            </form>
        </div>
    </div><!-- 左側、ログインエリアおわり -->

    <!-- 右側、会員登録エリア -->
    <div class="card col-md-6">
        <div class="card-body">
            <a href="{% url 'app:user_create' %}" class="btn btn-success btn-lg btn-block" >会員登録</a>
            <a href="{% url 'app:password_reset' %}" class="btn btn-success btn-lg btn-block" >パスワードを忘れた方</a>
        </div>
    </div><!-- 右側、会員登録エリアおわり -->
</div>
{% endblock %}

vuldb_portfolio/app/templates/app/password_change_done.html
{% extends "app/base.html" %}
{% block title %} パスワード変更完了 {% endblock %}
{% block content %}
<p>
    パスワードを変更しました。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'app:login' %}">ログイン</a>
</p>
{% endblock %}

vuldb_portfolio/app/templates/app/password_reset_confirm.html
{% extends "app/base.html" %}
{% block title %} パスワード再設定 {% endblock %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field_label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

vuldb_portfolio/app/templates/app/user_create_complete.html
{% extends "app/base.html" %}
{% block title %} 本登録完了 {% endblock %}
{% block content %}
<p>
    本登録が完了しました。<br>
    登録されたメールアドレスとパスワードでログインしてください。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'app:login' %}">ログイン</a>
</p>
{% endblock %}

vuldb_portfolio/app/templates/app/user_detail.html
{% extends "app/base.html" %}
{% block title %} {{ user.username }}のユーザー情報 {% endblock %}
{% block content %}
<div class="float-right">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'app:user_update' user.pk %}">プロフィール変更</a></li>
        <li class="breadcrumb-item"><a href="{% url 'app:email_change' %}">メールアドレス変更</a></li>
        <li class="breadcrumb-item"><a href="{% url 'app:password_change' %}">パスワード変更</a></li>
        <li class="breadcrumb-item"><a href="{% url 'app:user_delete' user.pk %}">退会</a></li>
    </ol>
</div>
<table class="table">
    <tbody>
        <tr>
            <th>メールアドレス</th>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th>ユーザー名</th>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <th>姓</th>
            <td>{{ user.last_name }}</td>
        </tr>
        <tr>
            <th>名</th>
            <td>{{ user.first_name }}</td>
        </tr>
    </tbody>
</table>
{% endblock %}

vuldb_portfolio/app/templates/app/user_form.html
{% extends "app/base.html" %}
{% block title %} {{ user.username }}のプロフィール変更 {% endblock %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    <table class="table">
        <tbody>
            {% for field in form %}
                <tr>
                    <th><label for="{{ field.id_for_label }}">{{ field.label }}</label></th>
                    <td>{{ field }} {{ field.errors }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-lg">変更</button>
</form>
{% endblock %}

vuldb_portfolio/app/templates/app/version_create.html
{% extends "app/base.html" %}
{% block title %} 新規バージョン登録 {% endblock %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">登録</button>
</form>
{% endblock %}

vuldb_portfolio/app/templates/app/version_detail.html
{% extends "app/base.html" %}
{% block title %} バージョン{{ object.version }}の詳細 {% endblock %}
{% block content %}
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>バージョン</th>
            <th>編集</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ object.version }}</td>
            <td>
                <div class="btn-group" role="group" aria-label="Basic example">
                    <a href="{% url 'app:version_update' object.pk %}" class="btn btn-warning">修正</a>
                    <a href="{% url 'app:version_delete' object.pk %}" class="btn btn-danger">削除</a>
                </div>
            </td>
        </tr>
    </tbody>
</table>
{% endblock %}